{
 "title": "Pool",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    { "expr": "avg(screenlogic_air_temp{})", "legendFormat": "Air" },
    {
     "expr": "avg by(name) (screenlogic_body_temp)",
     "legendFormat": "{{name}} (actual)"
    },
    {
     "expr": "avg by(name) (screenlogic_body_heat_setpoint)",
     "legendFormat": "{{name}} (setpoint)"
    }
   ]
  },
  {
   "title": "Circuits",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg by(name) (screenlogic_circuit_state)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pump",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "screenlogic_pump_rpm", "legendFormat": "RPM" },
    { "expr": "screenlogic_pump_gpm", "legendFormat": "GPM" }
   ]
  },
  {
   "title": "Heater Setting",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "avg by(name, screenlogic_body_heat_mode) (screenlogic_body_heat_mode)",
     "legendFormat": "{{name}}: {{screenlogic_body_heat_mode}}"
    }
   ]
  },
  {
   "title": "Heater State",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "avg by(name, screenlogic_body_heat_state) (screenlogic_body_heat_state)",
     "legendFormat": "{{name}}: {{screenlogic_body_heat_state}}"
    }
   ]
  }
 ]
}